# Site settings
title: SiGen
email: 18669893982@163.com
description: SiGen-- 一个小白的博客
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  ohmybuuug
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

port: 2333
# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false